### ISSUE TITLE
Taille de pseudo trop petits

### ISSUE THREAD

**Issue by Turdyo** [Mateleo/LolPros#4]
Tu vois que le pseudo passe sur 2 lignes, possible de fix ça en enlevant la width de ce bloc (120px) atm
![image](https://user-images.githubusercontent.com/63463668/192166921-6cb73a9b-2a5e-4eb8-add5-9fa8932396ba.png)

![image](https://user-images.githubusercontent.com/63463668/192166957-d91c0c3c-44bb-4cdf-b7ce-3801090a717c.png)

**Comment by Mateleo** [comment]
Je vais devoir disable la protection anti bouhahahahahahahahahaha
